name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Lua
      run: sudo apt-get install lua5.3

    - name: Install dependencies
      run: make install_dependencies

    - name: Run unit tests
      run: |
        make test
