name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Lua
        run: sudo apt-get install lua5.3

      - name: Install Lua development files
        run: sudo apt-get install liblua5.3-dev

      - name: Install Luarocks
        run: |
          sudo apt-get install luarocks

      - name: Configure Lua header files for Luarocks
        run: |
          export LUA_PATH=/usr/include/lua5.3
          export LUA_DIR=/usr/include/lua5.3
          sudo luarocks config variables.LUA_INCDIR /usr/include/lua5.3
          sudo luarocks config variables.LUA_LIBDIR /usr/lib/x86_64-linux-gnu
          sudo luarocks config variables.LUA_BINDIR /usr/bin

      - name: Install dependencies
        run: sudo make install_dependencies

      - name: Run unit tests
        run: |
          make test
